/********************************************************************************
** Form generated from reading UI file 'InputWidgetV.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_INPUTWIDGETV_H
#define UI_INPUTWIDGETV_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_InputWidgetV
{
public:
    QPushButton *bth_;
    QPushButton *btho;
    QPushButton *bthp;
    QPushButton *bthheng;
    QPushButton *btht;
    QPushButton *bthpoint;
    QPushButton *bth8;
    QPushButton *bthe;
    QPushButton *bthu;
    QPushButton *bthr;
    QPushButton *bth7;
    QPushButton *bth9;
    QPushButton *bthy;
    QPushButton *bthi;
    QPushButton *bthq;
    QPushButton *bth6;
    QPushButton *bthw;
    QPushButton *bth5;
    QPushButton *bth0;
    QPushButton *bth4;
    QPushButton *bths;
    QPushButton *bthg;
    QPushButton *bth3;
    QPushButton *bthh;
    QPushButton *bthdou;
    QPushButton *bthd;
    QPushButton *btha;
    QPushButton *bthj;
    QPushButton *bthf;
    QPushButton *bthk;
    QPushButton *bthz;
    QPushButton *bthx;
    QPushButton *bthc;
    QPushButton *bthv;
    QPushButton *bthn;
    QPushButton *bthm;
    QPushButton *bth1;
    QPushButton *bthda;
    QPushButton *bthBackspace;
    QPushButton *bthb;
    QPushButton *bth2;
    QPushButton *bthl;
    QPushButton *btn_1;
    QPushButton *btn_2;
    QPushButton *btn_3;
    QPushButton *btn_4;
    QPushButton *btn_5;
    QPushButton *btn_6;
    QPushButton *btn_7;
    QPushButton *btn_8;
    QPushButton *btn_9;
    QPushButton *btn_10;
    QPushButton *btn_11;
    QPushButton *btn_12;
    QPushButton *btn_13;
    QPushButton *btn_14;
    QPushButton *btn_15;
    QPushButton *btn_16;
    QPushButton *btn_17;
    QPushButton *btn_18;
    QPushButton *bthdou_2;
    QPushButton *bthdou_3;
    QPushButton *bth_1;
    QPushButton *bth_2;
    QPushButton *bth_3;
    QPushButton *bth_4;
    QPushButton *bth_5;
    QPushButton *bth_6;
    QPushButton *bth_7;

    void setupUi(QWidget *InputWidgetV)
    {
        if (InputWidgetV->objectName().isEmpty())
            InputWidgetV->setObjectName(QString::fromUtf8("InputWidgetV"));
        InputWidgetV->resize(316, 451);
        InputWidgetV->setFocusPolicy(Qt::NoFocus);
        bth_ = new QPushButton(InputWidgetV);
        bth_->setObjectName(QString::fromUtf8("bth_"));
        bth_->setGeometry(QRect(180, 0, 45, 45));
        bth_->setFocusPolicy(Qt::ClickFocus);
        btho = new QPushButton(InputWidgetV);
        btho->setObjectName(QString::fromUtf8("btho"));
        btho->setGeometry(QRect(180, 270, 45, 45));
        btho->setFocusPolicy(Qt::ClickFocus);
        bthp = new QPushButton(InputWidgetV);
        bthp->setObjectName(QString::fromUtf8("bthp"));
        bthp->setGeometry(QRect(0, 315, 45, 45));
        bthp->setFocusPolicy(Qt::ClickFocus);
        bthheng = new QPushButton(InputWidgetV);
        bthheng->setObjectName(QString::fromUtf8("bthheng"));
        bthheng->setGeometry(QRect(135, 135, 45, 45));
        btht = new QPushButton(InputWidgetV);
        btht->setObjectName(QString::fromUtf8("btht"));
        btht->setGeometry(QRect(180, 315, 45, 45));
        btht->setFocusPolicy(Qt::ClickFocus);
        bthpoint = new QPushButton(InputWidgetV);
        bthpoint->setObjectName(QString::fromUtf8("bthpoint"));
        bthpoint->setGeometry(QRect(45, 135, 45, 45));
        bthpoint->setFocusPolicy(Qt::ClickFocus);
        bth8 = new QPushButton(InputWidgetV);
        bth8->setObjectName(QString::fromUtf8("bth8"));
        bth8->setGeometry(QRect(45, 90, 45, 45));
        bth8->setFocusPolicy(Qt::ClickFocus);
        bthe = new QPushButton(InputWidgetV);
        bthe->setObjectName(QString::fromUtf8("bthe"));
        bthe->setGeometry(QRect(180, 180, 45, 45));
        bthe->setFocusPolicy(Qt::ClickFocus);
        bthu = new QPushButton(InputWidgetV);
        bthu->setObjectName(QString::fromUtf8("bthu"));
        bthu->setGeometry(QRect(0, 360, 45, 45));
        bthu->setFocusPolicy(Qt::ClickFocus);
        bthr = new QPushButton(InputWidgetV);
        bthr->setObjectName(QString::fromUtf8("bthr"));
        bthr->setGeometry(QRect(90, 315, 45, 45));
        bthr->setFocusPolicy(Qt::ClickFocus);
        bth7 = new QPushButton(InputWidgetV);
        bth7->setObjectName(QString::fromUtf8("bth7"));
        bth7->setGeometry(QRect(0, 90, 45, 45));
        bth7->setFocusPolicy(Qt::ClickFocus);
        bth9 = new QPushButton(InputWidgetV);
        bth9->setObjectName(QString::fromUtf8("bth9"));
        bth9->setGeometry(QRect(90, 90, 45, 45));
        bth9->setFocusPolicy(Qt::ClickFocus);
        bthy = new QPushButton(InputWidgetV);
        bthy->setObjectName(QString::fromUtf8("bthy"));
        bthy->setGeometry(QRect(180, 360, 45, 45));
        bthy->setFocusPolicy(Qt::ClickFocus);
        bthi = new QPushButton(InputWidgetV);
        bthi->setObjectName(QString::fromUtf8("bthi"));
        bthi->setGeometry(QRect(135, 225, 45, 45));
        bthi->setFocusPolicy(Qt::ClickFocus);
        bthq = new QPushButton(InputWidgetV);
        bthq->setObjectName(QString::fromUtf8("bthq"));
        bthq->setGeometry(QRect(45, 315, 45, 45));
        bthq->setFocusPolicy(Qt::ClickFocus);
        bth6 = new QPushButton(InputWidgetV);
        bth6->setObjectName(QString::fromUtf8("bth6"));
        bth6->setGeometry(QRect(90, 45, 45, 45));
        bth6->setFocusPolicy(Qt::ClickFocus);
        bthw = new QPushButton(InputWidgetV);
        bthw->setObjectName(QString::fromUtf8("bthw"));
        bthw->setGeometry(QRect(90, 360, 45, 45));
        bthw->setFocusPolicy(Qt::ClickFocus);
        bth5 = new QPushButton(InputWidgetV);
        bth5->setObjectName(QString::fromUtf8("bth5"));
        bth5->setGeometry(QRect(45, 45, 45, 45));
        bth5->setFocusPolicy(Qt::ClickFocus);
        bth0 = new QPushButton(InputWidgetV);
        bth0->setObjectName(QString::fromUtf8("bth0"));
        bth0->setGeometry(QRect(0, 135, 45, 45));
        bth0->setFocusPolicy(Qt::ClickFocus);
        bth4 = new QPushButton(InputWidgetV);
        bth4->setObjectName(QString::fromUtf8("bth4"));
        bth4->setGeometry(QRect(0, 45, 45, 45));
        bth4->setFocusPolicy(Qt::ClickFocus);
        bths = new QPushButton(InputWidgetV);
        bths->setObjectName(QString::fromUtf8("bths"));
        bths->setGeometry(QRect(135, 315, 45, 45));
        bths->setFocusPolicy(Qt::ClickFocus);
        bthg = new QPushButton(InputWidgetV);
        bthg->setObjectName(QString::fromUtf8("bthg"));
        bthg->setGeometry(QRect(45, 225, 45, 45));
        bthg->setFocusPolicy(Qt::ClickFocus);
        bth3 = new QPushButton(InputWidgetV);
        bth3->setObjectName(QString::fromUtf8("bth3"));
        bth3->setGeometry(QRect(90, 0, 45, 45));
        bth3->setFocusPolicy(Qt::ClickFocus);
        bthh = new QPushButton(InputWidgetV);
        bthh->setObjectName(QString::fromUtf8("bthh"));
        bthh->setGeometry(QRect(90, 225, 45, 45));
        bthh->setFocusPolicy(Qt::ClickFocus);
        bthdou = new QPushButton(InputWidgetV);
        bthdou->setObjectName(QString::fromUtf8("bthdou"));
        bthdou->setGeometry(QRect(270, 405, 45, 45));
        bthdou->setFocusPolicy(Qt::ClickFocus);
        bthd = new QPushButton(InputWidgetV);
        bthd->setObjectName(QString::fromUtf8("bthd"));
        bthd->setGeometry(QRect(135, 180, 45, 45));
        bthd->setFocusPolicy(Qt::ClickFocus);
        btha = new QPushButton(InputWidgetV);
        btha->setObjectName(QString::fromUtf8("btha"));
        btha->setGeometry(QRect(0, 180, 45, 45));
        btha->setFocusPolicy(Qt::ClickFocus);
        bthj = new QPushButton(InputWidgetV);
        bthj->setObjectName(QString::fromUtf8("bthj"));
        bthj->setGeometry(QRect(180, 225, 45, 45));
        bthj->setFocusPolicy(Qt::ClickFocus);
        bthf = new QPushButton(InputWidgetV);
        bthf->setObjectName(QString::fromUtf8("bthf"));
        bthf->setGeometry(QRect(0, 225, 45, 45));
        bthf->setFocusPolicy(Qt::ClickFocus);
        bthk = new QPushButton(InputWidgetV);
        bthk->setObjectName(QString::fromUtf8("bthk"));
        bthk->setGeometry(QRect(0, 270, 45, 45));
        bthk->setFocusPolicy(Qt::ClickFocus);
        bthz = new QPushButton(InputWidgetV);
        bthz->setObjectName(QString::fromUtf8("bthz"));
        bthz->setGeometry(QRect(0, 405, 45, 45));
        bthz->setFocusPolicy(Qt::ClickFocus);
        bthx = new QPushButton(InputWidgetV);
        bthx->setObjectName(QString::fromUtf8("bthx"));
        bthx->setGeometry(QRect(135, 360, 45, 45));
        bthx->setFocusPolicy(Qt::ClickFocus);
        bthc = new QPushButton(InputWidgetV);
        bthc->setObjectName(QString::fromUtf8("bthc"));
        bthc->setGeometry(QRect(90, 180, 45, 45));
        bthc->setFocusPolicy(Qt::ClickFocus);
        bthv = new QPushButton(InputWidgetV);
        bthv->setObjectName(QString::fromUtf8("bthv"));
        bthv->setGeometry(QRect(45, 360, 45, 45));
        bthv->setFocusPolicy(Qt::ClickFocus);
        bthn = new QPushButton(InputWidgetV);
        bthn->setObjectName(QString::fromUtf8("bthn"));
        bthn->setGeometry(QRect(135, 270, 45, 45));
        bthn->setFocusPolicy(Qt::ClickFocus);
        bthm = new QPushButton(InputWidgetV);
        bthm->setObjectName(QString::fromUtf8("bthm"));
        bthm->setGeometry(QRect(90, 270, 45, 45));
        bthm->setFocusPolicy(Qt::ClickFocus);
        bth1 = new QPushButton(InputWidgetV);
        bth1->setObjectName(QString::fromUtf8("bth1"));
        bth1->setGeometry(QRect(0, 0, 45, 45));
        bth1->setFocusPolicy(Qt::ClickFocus);
        bthda = new QPushButton(InputWidgetV);
        bthda->setObjectName(QString::fromUtf8("bthda"));
        bthda->setGeometry(QRect(45, 405, 90, 45));
        bthda->setFocusPolicy(Qt::ClickFocus);
        bthBackspace = new QPushButton(InputWidgetV);
        bthBackspace->setObjectName(QString::fromUtf8("bthBackspace"));
        bthBackspace->setGeometry(QRect(135, 405, 45, 45));
        bthBackspace->setFocusPolicy(Qt::ClickFocus);
        bthb = new QPushButton(InputWidgetV);
        bthb->setObjectName(QString::fromUtf8("bthb"));
        bthb->setGeometry(QRect(45, 180, 45, 45));
        bthb->setFocusPolicy(Qt::TabFocus);
        bth2 = new QPushButton(InputWidgetV);
        bth2->setObjectName(QString::fromUtf8("bth2"));
        bth2->setGeometry(QRect(45, 0, 45, 45));
        bth2->setFocusPolicy(Qt::ClickFocus);
        bthl = new QPushButton(InputWidgetV);
        bthl->setObjectName(QString::fromUtf8("bthl"));
        bthl->setGeometry(QRect(45, 270, 45, 45));
        btn_1 = new QPushButton(InputWidgetV);
        btn_1->setObjectName(QString::fromUtf8("btn_1"));
        btn_1->setGeometry(QRect(225, 45, 45, 45));
        btn_2 = new QPushButton(InputWidgetV);
        btn_2->setObjectName(QString::fromUtf8("btn_2"));
        btn_2->setGeometry(QRect(225, 90, 45, 45));
        btn_3 = new QPushButton(InputWidgetV);
        btn_3->setObjectName(QString::fromUtf8("btn_3"));
        btn_3->setGeometry(QRect(225, 135, 45, 45));
        btn_4 = new QPushButton(InputWidgetV);
        btn_4->setObjectName(QString::fromUtf8("btn_4"));
        btn_4->setGeometry(QRect(225, 180, 45, 45));
        btn_5 = new QPushButton(InputWidgetV);
        btn_5->setObjectName(QString::fromUtf8("btn_5"));
        btn_5->setGeometry(QRect(225, 225, 45, 45));
        btn_6 = new QPushButton(InputWidgetV);
        btn_6->setObjectName(QString::fromUtf8("btn_6"));
        btn_6->setGeometry(QRect(225, 270, 45, 45));
        btn_7 = new QPushButton(InputWidgetV);
        btn_7->setObjectName(QString::fromUtf8("btn_7"));
        btn_7->setGeometry(QRect(135, 45, 45, 45));
        btn_8 = new QPushButton(InputWidgetV);
        btn_8->setObjectName(QString::fromUtf8("btn_8"));
        btn_8->setGeometry(QRect(225, 315, 45, 45));
        btn_9 = new QPushButton(InputWidgetV);
        btn_9->setObjectName(QString::fromUtf8("btn_9"));
        btn_9->setGeometry(QRect(225, 360, 45, 45));
        btn_10 = new QPushButton(InputWidgetV);
        btn_10->setObjectName(QString::fromUtf8("btn_10"));
        btn_10->setGeometry(QRect(270, 315, 45, 45));
        btn_11 = new QPushButton(InputWidgetV);
        btn_11->setObjectName(QString::fromUtf8("btn_11"));
        btn_11->setGeometry(QRect(270, 180, 45, 45));
        btn_12 = new QPushButton(InputWidgetV);
        btn_12->setObjectName(QString::fromUtf8("btn_12"));
        btn_12->setGeometry(QRect(270, 360, 45, 45));
        btn_13 = new QPushButton(InputWidgetV);
        btn_13->setObjectName(QString::fromUtf8("btn_13"));
        btn_13->setGeometry(QRect(90, 135, 45, 45));
        btn_14 = new QPushButton(InputWidgetV);
        btn_14->setObjectName(QString::fromUtf8("btn_14"));
        btn_14->setGeometry(QRect(270, 90, 45, 45));
        btn_15 = new QPushButton(InputWidgetV);
        btn_15->setObjectName(QString::fromUtf8("btn_15"));
        btn_15->setGeometry(QRect(135, 90, 45, 45));
        btn_16 = new QPushButton(InputWidgetV);
        btn_16->setObjectName(QString::fromUtf8("btn_16"));
        btn_16->setGeometry(QRect(270, 135, 45, 45));
        btn_17 = new QPushButton(InputWidgetV);
        btn_17->setObjectName(QString::fromUtf8("btn_17"));
        btn_17->setGeometry(QRect(135, 0, 45, 45));
        btn_18 = new QPushButton(InputWidgetV);
        btn_18->setObjectName(QString::fromUtf8("btn_18"));
        btn_18->setGeometry(QRect(180, 90, 45, 45));
        bthdou_2 = new QPushButton(InputWidgetV);
        bthdou_2->setObjectName(QString::fromUtf8("bthdou_2"));
        bthdou_2->setGeometry(QRect(270, 270, 45, 45));
        bthdou_2->setFocusPolicy(Qt::ClickFocus);
        bthdou_3 = new QPushButton(InputWidgetV);
        bthdou_3->setObjectName(QString::fromUtf8("bthdou_3"));
        bthdou_3->setGeometry(QRect(270, 225, 45, 45));
        bthdou_3->setFocusPolicy(Qt::ClickFocus);
        bth_1 = new QPushButton(InputWidgetV);
        bth_1->setObjectName(QString::fromUtf8("bth_1"));
        bth_1->setGeometry(QRect(225, 0, 45, 45));
        bth_1->setFocusPolicy(Qt::ClickFocus);
        bth_2 = new QPushButton(InputWidgetV);
        bth_2->setObjectName(QString::fromUtf8("bth_2"));
        bth_2->setGeometry(QRect(270, 0, 45, 45));
        bth_2->setFocusPolicy(Qt::ClickFocus);
        bth_3 = new QPushButton(InputWidgetV);
        bth_3->setObjectName(QString::fromUtf8("bth_3"));
        bth_3->setGeometry(QRect(270, 45, 45, 45));
        bth_3->setFocusPolicy(Qt::ClickFocus);
        bth_4 = new QPushButton(InputWidgetV);
        bth_4->setObjectName(QString::fromUtf8("bth_4"));
        bth_4->setGeometry(QRect(180, 45, 45, 45));
        bth_4->setFocusPolicy(Qt::ClickFocus);
        bth_5 = new QPushButton(InputWidgetV);
        bth_5->setObjectName(QString::fromUtf8("bth_5"));
        bth_5->setGeometry(QRect(180, 135, 45, 45));
        bth_5->setFocusPolicy(Qt::ClickFocus);
        bth_6 = new QPushButton(InputWidgetV);
        bth_6->setObjectName(QString::fromUtf8("bth_6"));
        bth_6->setGeometry(QRect(180, 405, 45, 45));
        bth_6->setFocusPolicy(Qt::ClickFocus);
        bth_7 = new QPushButton(InputWidgetV);
        bth_7->setObjectName(QString::fromUtf8("bth_7"));
        bth_7->setGeometry(QRect(225, 405, 45, 45));
        bth_7->setFocusPolicy(Qt::ClickFocus);
        bth_7->setStyleSheet(QString::fromUtf8("image: url(:/images/btn_yu.png);"));

        retranslateUi(InputWidgetV);

        QMetaObject::connectSlotsByName(InputWidgetV);
    } // setupUi

    void retranslateUi(QWidget *InputWidgetV)
    {
        InputWidgetV->setWindowTitle(QApplication::translate("InputWidgetV", "Form", 0, QApplication::UnicodeUTF8));
        bth_->setText(QApplication::translate("InputWidgetV", "_", 0, QApplication::UnicodeUTF8));
        btho->setText(QApplication::translate("InputWidgetV", "o", 0, QApplication::UnicodeUTF8));
        bthp->setText(QApplication::translate("InputWidgetV", "p", 0, QApplication::UnicodeUTF8));
        bthheng->setText(QApplication::translate("InputWidgetV", "-", 0, QApplication::UnicodeUTF8));
        btht->setText(QApplication::translate("InputWidgetV", "t", 0, QApplication::UnicodeUTF8));
        bthpoint->setText(QApplication::translate("InputWidgetV", ".", 0, QApplication::UnicodeUTF8));
        bth8->setText(QApplication::translate("InputWidgetV", "8", 0, QApplication::UnicodeUTF8));
        bthe->setText(QApplication::translate("InputWidgetV", "e", 0, QApplication::UnicodeUTF8));
        bthu->setText(QApplication::translate("InputWidgetV", "u", 0, QApplication::UnicodeUTF8));
        bthr->setText(QApplication::translate("InputWidgetV", "r", 0, QApplication::UnicodeUTF8));
        bth7->setText(QApplication::translate("InputWidgetV", "7", 0, QApplication::UnicodeUTF8));
        bth9->setText(QApplication::translate("InputWidgetV", "9", 0, QApplication::UnicodeUTF8));
        bthy->setText(QApplication::translate("InputWidgetV", "y", 0, QApplication::UnicodeUTF8));
        bthi->setText(QApplication::translate("InputWidgetV", "i", 0, QApplication::UnicodeUTF8));
        bthq->setText(QApplication::translate("InputWidgetV", "q", 0, QApplication::UnicodeUTF8));
        bth6->setText(QApplication::translate("InputWidgetV", "6", 0, QApplication::UnicodeUTF8));
        bthw->setText(QApplication::translate("InputWidgetV", "w", 0, QApplication::UnicodeUTF8));
        bth5->setText(QApplication::translate("InputWidgetV", "5", 0, QApplication::UnicodeUTF8));
        bth0->setText(QApplication::translate("InputWidgetV", "0", 0, QApplication::UnicodeUTF8));
        bth4->setText(QApplication::translate("InputWidgetV", "4", 0, QApplication::UnicodeUTF8));
        bths->setText(QApplication::translate("InputWidgetV", "s", 0, QApplication::UnicodeUTF8));
        bthg->setText(QApplication::translate("InputWidgetV", "g", 0, QApplication::UnicodeUTF8));
        bth3->setText(QApplication::translate("InputWidgetV", "3", 0, QApplication::UnicodeUTF8));
        bthh->setText(QApplication::translate("InputWidgetV", "h", 0, QApplication::UnicodeUTF8));
        bthdou->setText(QApplication::translate("InputWidgetV", ",", 0, QApplication::UnicodeUTF8));
        bthd->setText(QApplication::translate("InputWidgetV", "d", 0, QApplication::UnicodeUTF8));
        btha->setText(QApplication::translate("InputWidgetV", "a", 0, QApplication::UnicodeUTF8));
        bthj->setText(QApplication::translate("InputWidgetV", "j", 0, QApplication::UnicodeUTF8));
        bthf->setText(QApplication::translate("InputWidgetV", "f", 0, QApplication::UnicodeUTF8));
        bthk->setText(QApplication::translate("InputWidgetV", "k", 0, QApplication::UnicodeUTF8));
        bthz->setText(QApplication::translate("InputWidgetV", "z", 0, QApplication::UnicodeUTF8));
        bthx->setText(QApplication::translate("InputWidgetV", "x", 0, QApplication::UnicodeUTF8));
        bthc->setText(QApplication::translate("InputWidgetV", "c", 0, QApplication::UnicodeUTF8));
        bthv->setText(QApplication::translate("InputWidgetV", "v", 0, QApplication::UnicodeUTF8));
        bthn->setText(QApplication::translate("InputWidgetV", "n", 0, QApplication::UnicodeUTF8));
        bthm->setText(QApplication::translate("InputWidgetV", "m", 0, QApplication::UnicodeUTF8));
        bth1->setText(QApplication::translate("InputWidgetV", "1", 0, QApplication::UnicodeUTF8));
        bthda->setText(QApplication::translate("InputWidgetV", "shift", 0, QApplication::UnicodeUTF8));
        bthBackspace->setText(QApplication::translate("InputWidgetV", "DEL", 0, QApplication::UnicodeUTF8));
        bthb->setText(QApplication::translate("InputWidgetV", "b", 0, QApplication::UnicodeUTF8));
        bth2->setText(QApplication::translate("InputWidgetV", "2", 0, QApplication::UnicodeUTF8));
        bthl->setText(QApplication::translate("InputWidgetV", "l", 0, QApplication::UnicodeUTF8));
        btn_1->setText(QApplication::translate("InputWidgetV", "!", 0, QApplication::UnicodeUTF8));
        btn_2->setText(QApplication::translate("InputWidgetV", "@", 0, QApplication::UnicodeUTF8));
        btn_3->setText(QApplication::translate("InputWidgetV", "#", 0, QApplication::UnicodeUTF8));
        btn_4->setText(QApplication::translate("InputWidgetV", "$", 0, QApplication::UnicodeUTF8));
        btn_5->setText(QApplication::translate("InputWidgetV", "%", 0, QApplication::UnicodeUTF8));
        btn_6->setText(QApplication::translate("InputWidgetV", "^", 0, QApplication::UnicodeUTF8));
        btn_7->setText(QApplication::translate("InputWidgetV", "*", 0, QApplication::UnicodeUTF8));
        btn_8->setText(QApplication::translate("InputWidgetV", "(", 0, QApplication::UnicodeUTF8));
        btn_9->setText(QApplication::translate("InputWidgetV", ")", 0, QApplication::UnicodeUTF8));
        btn_10->setText(QApplication::translate("InputWidgetV", "{", 0, QApplication::UnicodeUTF8));
        btn_11->setText(QApplication::translate("InputWidgetV", ">", 0, QApplication::UnicodeUTF8));
        btn_12->setText(QApplication::translate("InputWidgetV", "}", 0, QApplication::UnicodeUTF8));
        btn_13->setText(QApplication::translate("InputWidgetV", "=", 0, QApplication::UnicodeUTF8));
        btn_14->setText(QApplication::translate("InputWidgetV", ";", 0, QApplication::UnicodeUTF8));
        btn_15->setText(QApplication::translate("InputWidgetV", "+", 0, QApplication::UnicodeUTF8));
        btn_16->setText(QApplication::translate("InputWidgetV", "<", 0, QApplication::UnicodeUTF8));
        btn_17->setText(QApplication::translate("InputWidgetV", "/", 0, QApplication::UnicodeUTF8));
        btn_18->setText(QApplication::translate("InputWidgetV", "\"", 0, QApplication::UnicodeUTF8));
        bthdou_2->setText(QApplication::translate("InputWidgetV", "]", 0, QApplication::UnicodeUTF8));
        bthdou_3->setText(QApplication::translate("InputWidgetV", "[", 0, QApplication::UnicodeUTF8));
        bth_1->setText(QApplication::translate("InputWidgetV", "|", 0, QApplication::UnicodeUTF8));
        bth_2->setText(QApplication::translate("InputWidgetV", "\\", 0, QApplication::UnicodeUTF8));
        bth_3->setText(QApplication::translate("InputWidgetV", ":", 0, QApplication::UnicodeUTF8));
        bth_4->setText(QApplication::translate("InputWidgetV", "'", 0, QApplication::UnicodeUTF8));
        bth_5->setText(QApplication::translate("InputWidgetV", "?", 0, QApplication::UnicodeUTF8));
        bth_6->setText(QApplication::translate("InputWidgetV", "~", 0, QApplication::UnicodeUTF8));
        bth_7->setText(QApplication::translate("InputWidgetV", "&&", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class InputWidgetV: public Ui_InputWidgetV {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_INPUTWIDGETV_H
